FROM node:26-alpine3.23

RUN npm install -g pnpm@11

WORKDIR /app

COPY ./package.json ./
COPY ./pnpm-lock.yaml ./
COPY ./tsconfig.json ./
COPY ./vite.config.ts ./
COPY ./postcss.config.js ./
COPY ./index.html ./
COPY ./pnpm-workspace.yaml ./
COPY ./assets ./assets
COPY ./public ./public

RUN pnpm install

EXPOSE 3000

CMD ["pnpm", "run", "dev"]
